services:
  frontend:
    build: .
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
      - /frontend/node_modules
    command: npm run dev
    networks:
      - app_net
