services:
  backend_user_service:
    &backend
    env_file: .env
    build: .
    restart: always
    container_name: backend_user_service
    volumes:
      - .:/backend
      - ./certs:/backend/certs:ro
    working_dir: /backend
    environment:
      - PYTHONPATH=src
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - APP_MODE=${APP_MODE}
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - APP_NAME=${APP_NAME}
    # command: sh -c "alembic upgrade head && uvicorn run:make_app --factory --host ${APP_HOST} --port ${APP_PORT} --reload"
    command: sh -c "uvicorn run:make_app --factory --host ${APP_HOST} --port ${APP_PORT} --reload"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db_user_service:
        condition: service_healthy
      rabbitmq_user_service:
        condition: service_healthy
      redis_user_service:
        condition: service_healthy
    networks:
      - app_net

  rabbitmq_user_service:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq_user_service
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_user_service_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 10s
      timeout: 5s
      retries: 8
    networks:
      - app_net

  worker_user_service:
    <<: *backend
    container_name: worker_user_service
    ports: []
    command: taskiq worker core:broker --workers 1 --fs-discover --tasks-pattern **/tasks/*.py
    networks:
      - app_net

  db_user_service:
    env_file: .env
    image: postgres:18-alpine
    container_name: db_user_service
    volumes:
      - db_user_service_data:/var/lib/postgresql
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net
    restart: always

  redis_user_service:
    image: redis:8-alpine
    container_name: redis_user_service
    ports:
      - "6381:6379"
    volumes:
      - redis_user_service_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net

volumes:
  db_user_service_data:
  redis_user_service_data:
  rabbitmq_user_service_data: